@hostname = localhost 
@port = 5101 
@host = https://{{hostname}}:{{port}} 
@contentType = application/json

### GET {{host}}/api/users
GET {{host}}/api/users

### GET {{host}}/api/users/3
GET {{host}}/api/users/3

### DELETE {{host}}/api/users/0
DELETE {{host}}/api/users/0

### POST {{host}}/api/users Content-Type: {{contentType}}
POST {{host}}/api/users
Content-Type: {{contentType}}

{
"id" : 1, "FirstName": "Keith", "LastName": "Emerson"

}

### PUT {{host}}/api/users/1 Content-Type: {{contentType}}
PUT {{host}}/api/users/1
Content-Type: {{contentType}}

{
"id" : 1, "FirstName": "John", "LastName": "Lord"

}